name: "🚀 Epic / Global Feature"
description: "Создать крупную функциональность, состоящую из нескольких подзадач"
title: "[Epic]: "
labels: ["epic", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🚀 **Epic / Global Feature**
        ---
        Используй этот шаблон для больших фич, которые состоят из нескольких связанных задач или направлений разработки.

  - type: input
    id: epic-title
    attributes:
      label: "🎯 Название эпика"
      placeholder: "Например: Генерация изображения по текстовому промту"
    validations:
      required: true

  - type: textarea
    id: epic-goal
    attributes:
      label: "🧩 Цель"
      placeholder: "Опиши основную цель эпика и какую проблему он решает."
      value: |
        Реализовать систему генерации изображений на основе промтов с серверным взаимодействием, настройками и UI.
    validations:
      required: true

  - type: textarea
    id: epic-description
    attributes:
      label: "📘 Описание"
      description: "Опиши общую идею, архитектуру и ключевые компоненты."
      placeholder: "Подключение к серверу, WebSocket, обработка промтов, UI отображение, кэширование, и т.д."
    validations:
      required: true

  - type: textarea
    id: epic-subtasks
    attributes:
      label: "✅ Подзадачи"
      description: "Разбей эпик на конкретные GitHub Issues (или добавь как чеклист)."
      placeholder: |
        - [ ] #12 — Подключение к серверу и WebSocket
        - [ ] #13 — Обработка positive/negative промтов
        - [ ] #14 — Получение изображения с сервера
        - [ ] #15 — Конфигурация генерации (CFG, шаги, шум)
        - [ ] #16 — UI экран генерации
      value: |
        - [ ] Добавить подключение к серверу и WebSocket
        - [ ] Реализовать парсинг и валидацию промтов
        - [ ] Получать изображение с сервера
        - [ ] Добавить настройки генерации (CFG, шаги, шум)
        - [ ] Разработать UI интерфейс
    validations:
      required: true

  - type: textarea
    id: epic-extensions
    attributes:
      label: "💡 Идеи и расширения"
      placeholder: "Например: история генераций, кэширование изображений, seed, стилизация результата и т.д."

  - type: textarea
    id: epic-technologies
    attributes:
      label: "🧰 Технологии"
      placeholder: "Kotlin, Jetpack Compose, Retrofit, WebSocket, MVI, Coroutines, DataStore..."
      value: |
        - Kotlin + Jetpack Compose
        - Retrofit / OkHttp
        - WebSocket
        - MVI Architecture
        - Coroutines / Flow

  - type: textarea
    id: epic-relations
    attributes:
      label: "🔗 Связанные задачи / зависимости"
      placeholder: "Например: #10 (Server API), #7 (Auth system), #22 (UI redesign)"