name: "🚀 Feature Request"
description: "Предложить новую функциональность или улучшение"
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что предлагаешь улучшение для проекта 🙌  
        Пожалуйста, заполни детали ниже как можно подробнее.

  - type: input
    id: feature-title
    attributes:
      label: "🎯 Краткое описание фичи"
      placeholder: "Например: Генерация изображения по текстовому промту"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: "🧩 Подробное описание"
      placeholder: "Опиши, что именно нужно реализовать и зачем"
    validations:
      required: true

  - type: textarea
    id: feature-subtasks
    attributes:
      label: "✅ Подзадачи"
      description: "Разбей фичу на конкретные шаги"
      placeholder: |
        - [ ] Подключение к серверу
        - [ ] Добавить positive/negative промты
        - [ ] Получение изображения с сервера
        - [ ] Добавить UI
    validations:
      required: true

  - type: textarea
    id: feature-extra
    attributes:
      label: "💡 Дополнительные идеи"
      placeholder: "Например: добавить кэширование, историю, seed, стили и т.д."

  - type: textarea
    id: technologies
    attributes:
      label: "🧰 Используемые технологии"
      placeholder: "Kotlin, Jetpack Compose, Retrofit, WebSocket, MVI, DataStore..."